version: '3'

services:
  db:
    image: postgres

    container_name: event-hub-postgres

    restart: always

    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: event-hub
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwrd
